### PR TITLE
WIP Svg export

### LINKED ISSUE #18: Add SVG export feature, wherein selected graphics can be exported to a file.

### PR DESCRIPTION
**Pull request by curran**
Will close #18

### CODE REVIEW

**Comment by curran** [comment]
Currently an SVG gets downloaded, but the colors are missing:

image

**Comment by seemantk** [comment]
Artistically, I dig the way that looks in black and white!

**Comment by curran** [comment]
Haha right!? #d3brokeandmadeart

**Comment by seemantk** [comment]
Update: mbostock has released [svjimmy](https://github.com/mbostock/svjimmy).  He was kind enough to consider the use case we present here, and accordingly [made it work for us](https://github.com/mbostock/svjimmy/issues/1#issuecomment-278422712). I assume we can either recommend that Jesse use that, or we can [borrow](https://github.com/mbostock/svjimmy/blob/master/LICENSE) the [code](https://github.com/mbostock/svjimmy/blob/master/index.js), which is really rather small.

**Comment by curran** [comment]
Closing in favor of #108

**Pull request closed without merging**
