### PR TITLE
D3v4

### PR DESCRIPTION
**Pull request by seemantk**
Pushing this broken incomplete v4 migration. @curran hopefully you can see where I went wrong.

### CODE REVIEW

**Comment by curran** [comment]
Feels like too much going on here at once. Maybe let's first refactor to use dispatch with the zooming in the v3 trunk (gh-pages), then migrate to v4? Lots of ideas here though that we can draw from, thanks for going for it!

**Comment by seemantk** [comment]
@curran please review this and the previous pull request (refactoring), as then we are at d3v4 with a working viz.
Cheers!

**Comment by curran** [comment]
Looks awesome! Thanks for this great work. I'll go ahead and merge both PRs.

**Comment by curran** [comment]
It looks like this branch was rebased off the other one (refactor), so I believe merging only this one will also include all the changes from #36. I'll go ahead and merge this one, and close #36 without merging it.

**Comment by seemantk** [comment]
Tooltips have broken in this update.

**Pull request merged**
