### PR TITLE
Before Reskeleton

### PR DESCRIPTION
**Pull request by seemantk**
This works finally!  The nav and the main view use the same coordinate systems even. In fact, the nav and main view are constructed identically -- the only thing that separates them is the viewBox of their outermost SVG containers.  The nav encloses the entire contents, while the main view shows a window on a portion.
(The nav's matches the contents' viewBoxes, while the main view's viewBox changes with the brush).

Ready for your review, @curran.

### CODE REVIEW

**Comment by curran** [comment]
@seemantk I took a dive through the code here, and overall I think the approach is really cool. The resizing for the focus view is nice, as it always presents the notes as non-distorted. The resizing for the context view sort of squishes the notes. It appears you've also fixed **Fix positioning of highest notes** #75 with these changes too!

Here are the things that seem necessary to do in order to restore the functionality that was present before this refactoring:
- [ ] Reinstate the combine-separate interaction. I attempted to do this but got tripped up with the relocation of scales into `Score`.
- [ ] Reinstate show/hide extreme notes
- [ ] Reinstate show/hide notes
- [ ] Reinstate show/hide notes ribbons
- [ ] Reinstate voice selection interaction
- [ ] Make the X extent of the focus view match the brush extent. Or, maybe we can look into changing the brush to a line if we want to remove the actual zooming behavior. My gut feeling is it would be best to keep the zooming.
- [ ] Make the scaling of the context view depend only on the width, so as to preserve the aspect ratio all the time (maybe).

**Comment by curran** [comment]
Created #84 as a temporary way to demo the progress made here on responsiveness.

**Comment by seemantk** [comment]
@curran, thanks for diving! The code is still a bit transitional -- I hope to have you a settled down version in the next couple of evenings (my timezone).  The highest notes thing was purely by accident, but I'm glad that worked out!

As far as the context view (aka mininav), you're 100% right: most of the time, it will be distorted.  The width:height ratio of each piece of music is different.  So, just to be sure:
1. The focus view's notes come in sized according to the focus containter's _height_.  This gives us a window with the focus view's relative width onto the music, and we can slide along it no matter how long the piece is.
2. The context view's notes, on the other hand, come in sized to the context container's _width_ -- because the mininav must remain in full view no matter how long the piece  is.  Its aspect ratio becomes a victim to that requirement.

To adhere to aspect ratio, simply comment [out setting the nav's preservedAspectRatio](https://github.com/sul-cidr/josquin-ribbon/blob/ee2198de37fecccad6f4c074e2ac4b4e0e013155/js/baton.js#L68).

Here's  the default song (the available svg real estate is highlighted).
match-ar-nav-default-song

Here's a long song (Jos 1913 of course!):
match-ar-nav-long-song

**Comment by seemantk** [comment]
I think these conflicts are due to this being branched off shadow.

**Comment by seemantk** [comment]
This deprecates and thus closes #82

**Comment by seemantk** [comment]
Renamed the PR.  This was along the way of the actual reskeleton work.  That's the next push.

**Pull request closed without merging**
