### PR TITLE
Tooltips

### PR DESCRIPTION
**Pull request by seemantk**
Re-enable tooltips

### CODE REVIEW

**Comment by seemantk** [comment]
@curran, this is ready for your review.

**Comment by curran** [comment]
Hi @seemantk , I ran the branch and I'm not seeing tooltips. The Tooltip DIV is there in the DOM, but it's empty and not populated on hover.

**Comment by curran** [comment]
After some debugging, it seems that the `tooltip && svg` check never succeeds:

``` js
    function enableTooltips() {
        console.log("enableTooltips");
        if(tooltip && svg) {
            console.log("inside"); // Never gets printed
```

**Comment by curran** [comment]
Passing in the tooltip on init made everything work ([diff](https://github.com/sul-cidr/josquin-ribbon/pull/51/commits/a6892db69b3c728fbc8c88e2c77cc3df1ecbe272)).

**Comment by seemantk** [comment]
Thanks for sorting that out, Curran. Not sre why/when that went away.  Great job finding/debugging

**Pull request merged**
