### PR TITLE
Fabulize

### PR DESCRIPTION
**Pull request by seemantk**
Add FAB with flyouts. FAB = fixed action button, and use the material lite styles.

### CODE REVIEW

**Comment by seemantk** [comment]
@curran this is very basic functionality for the buttons, but I wanted to ensure your eyes on this early as possible.  TODO: tooltips, button states (active, disabled, etc), and transitions.

**Comment by curran** [comment]
@seemantk This looks fabulous! Awesome UI redesign.

**Comment by curran** [comment]
@seemantk This is great, should we merge it? I was holding off as it is WIP, just wondering if you plan to add more here in this PR.

**Comment by seemantk** [comment]
@curran, I think this is mergeable, now that you mention it.  I have more work around the buttons, like styling and states (buttons up and down states).  Also, we have two paired things (combine/separate and std.dev/attack-density) -- the button treatment in this PR doesn't really address those in an intuitive manner yet. 

Having said all that, please feel free to merge if you think it's a good enough replacement for what we have now.  thanks!

**Comment by curran** [comment]
I feel this is a great improvement. All we need on top of this is probably tooltips, to clarify what each button does.

**Pull request merged**
