### PR TITLE
Remerge from deep shadow

### PR DESCRIPTION
**Pull request by seemantk**
@curran, thank you for your help landing this, this week.

This is now working with most of the markings, except for reflines, which is still static (doens't split yet).

There are two things which need to be done after this merge:

  - Section labels
  - Section lines
  - (in addition to dynamic reflines).

Please merge this for demoing to the team.

### CODE REVIEW

**Comment by curran** [comment]
@seemantk I will have a look and see if I can restore the calculation.

**Comment by curran** [comment]
This is what I'm seeing:

image

The standard deviation ribbons seem to be rendering correctly? There are a few other issues though that are popping out:

 * The navigation view is showing nothing (only the brush)
 * The labels are distorted
 * The menu shows "Standard Deviatio" (maybe this is a browser-specific thing)

I will see if I can restore rendering of the navigation view.

**Comment by seemantk** [comment]
@curran yes, I've got the navigation image disabled at the moment.  The std dev ribbons look very different from what's on ribbon.humdrum  (the ribbons are very thick).

I'm still working through things, and pushing, so the nav update is coming too.

**Comment by curran** [comment]
@seemantk Ah yes I see what you mean. Will investigate further. I just pushed a commit here (sorry, was not aware you are working presently).

**Comment by curran** [comment]
@seemantk Got it - the trick was that `duration` had changed from a number to an array.

image

**Comment by curran** [comment]
This looks fantastic @seemantk ! Will merge.

**Pull request merged**
