### PR TITLE
Export svg

### LINKED ISSUE #18: Add SVG export feature, wherein selected graphics can be exported to a file.

### PR DESCRIPTION
**Pull request by curran**
Closes #18 using [SVGSaver](https://github.com/Hypercubed/svgsaver)

### CODE REVIEW

**Comment by curran** [comment]
@seemantk Ready for review. One more commit incoming, to customize the file name, but please take a look if you can :)

**Comment by curran** [comment]
@seemantk Done.

**Comment by curran** [comment]
Merging for demoability.

**Comment by seemantk** [comment]
@curran, this works great!  I've noticed a couple of things:

Downloading the larger SVG (jos1913) fails for me (all from localhost):
1913download

The smaller/default piece downloads great!

It looks slightly grainy:
grainy

I noticed other things that need to be addressed as part of the text zoom/scale stuff:
First of all, the reflines SVG is way too large

After removing them, and ungrouping the rest of the items, all things display:
unpacked

Which brings up a question: should we exclude ribbons entirely from the download?

**Pull request merged**
