### PR TITLE
This made notes appear in the right places for me; ymmv

### PR DESCRIPTION
**Pull request by broadwell**
Sorry, kind of filing this on the run, but FYI the notes seemed to be misaligned with the staff when using the `move-panel` branch. After making these adjustments, everything appears to be in the right place -- but please check it out and let me know if you see the difference.
I'll try to add screenshots later that hopefully will support my case.

### CODE REVIEW

**Comment by broadwell** [comment]
Never mind -- can't reproduce. Probably it was a caching issue and/or due to a poor wifi connection. Will do a bit more testing before merging this in; then I'll do one or two PRs to add the aggregate voice and rhythmic ribbon centering.

**Comment by broadwell** [comment]
Oh wait, after a fresh checkout and comparison, it's back. See forthcoming screenshots. The problem may be more prevalent when the entire layout doesn't fit in the browser window.

**Comment by broadwell** [comment]
With `move-panel` -- the notes are positioned too high:
Screenshot 2019-11-08 16 54 19
After merging `move_panel_2`:
Screenshot 2019-11-08 16 55 06

**Comment by simonwiles** [comment]
Is it this value here?

https://github.com/sul-cidr/josquin-ribbon/blob/c67c4f23a836de7d369f3813ef10ac5ae30e7314/js/dev/notesbook.js#L11

With this value set to `0`, are the notes in the right place?  If so, there are a couple of solutions I can think of, but let's pin it down first.

**Comment by broadwell** [comment]
OK yeah, setting `voicesHaxisOffset = 0` also makes the notes appear in the right places, so it's quite possible that the other suggested changes in this PR aren't necessary to address it.

FYI, though, the change
`-      y.domain(d3.range(data.minpitch.b7, data.maxpitch.b7 + 1))`
`+      y.domain(d3.range(16,40))`

Is something that will need to be added later (via another PR that I'd submit) to improve the positioning of the staves -- but it doesn't influence the placement of the notes.

**Comment by broadwell** [comment]
This is addressed in other PRs

**Pull request closed without merging**
