### PR TITLE
Dematerialize

### PR DESCRIPTION
**Pull request by seemantk**
Sorry for the late news here @curran, but I'm just finishing this one up.  Will remove the "WIP" flag when ready.

### CODE REVIEW

**Comment by curran** [comment]
@seemantk This is fantastic! Thanks for this. Will review once out of WIP.

By the way I made some README changes in #101 in case you missed it.

**Comment by seemantk** [comment]
@curran -- functionality isn't perfect, but I think it can be demoed.  Please review and merge at your discretion.

**Comment by curran** [comment]
@seemantk Any chance you could massage the UI/UX a bit more here?

This is what the layout looks like for me:
image

UX-wise, the interactions with the button with the menu inside it are tricky at the moment.

**Comment by seemantk** [comment]
@curran, pushed #106 to fix the control set here.

**Pull request merged**
