### PR TITLE
Strip the panner element from exported SVGs

### PR DESCRIPTION
**Pull request by simonwiles**

### CODE REVIEW

**Comment by broadwell** [comment]
Uh oh, now it looks like removing the `panner` element  takes out the ribbons and notes elements underneath it.
Note also that there is a mismatch between the horizontal scale of the markings and the scale of the ribbons and notes -- this view covers approximately the first 12 bars of the song, not the first 85.
Screenshot 2019-11-26 11 29 16

**Comment by simonwiles** [comment]
Which score is that?  Because all of my tests look fine (that that behaviour makes no sense at all!)

before:
image


after:
image

(and opening the SVG in a browser and deleting the offending `<rect/>` element also works as expected...)

**Comment by broadwell** [comment]
I've been testing with Jos1803. I haven't been able to get the blank left-side notes/ribbons content problem to reproduce consistently, but the scale of the exported SVG consistently goes out of whack whenever I change the size of the brush/zoom window in the bottom navigator strip before exporting -- so that may be where to check first.

**Comment by simonwiles** [comment]
I've ticketed this related issue as #226, and am going to merge this.

**Pull request merged**
