### PR TITLE
WIP SVG Markings Export

### PR DESCRIPTION
**Pull request by curran**

### CODE REVIEW

**Comment by curran** [comment]
This is what the current code does if we try to export the top-level SVG:

image

The notes respond to resize in the exported SVG, this is the main issue why they don't line up.

@seemantk Any thoughts on directions here? Maybe we could disable the viewbox and preserveAspectRatio settings before exporting? Not sure..

**Comment by seemantk** [comment]
Hi Curran,

I believe your instinct is correct on the viewbox preservation.

Cheers,
Seemant

**Comment by craigsapp** [comment]
An interesting possibility is to use pdfkit to export the image.  Multiple SVG images should be able to overwrite each other:

http://pdfkit.org

Online demo:

http://pdfkit.org/demo/browser.html

I implemented PDF export for VHV today, using this code:

https://github.com/humdrum-tools/verovio-humdrum-viewer/blob/gh-pages/_includes/pdfkit.html

I only write a single image on each page, such as in the multi-page function,  generatePdfFull:

https://github.com/humdrum-tools/verovio-humdrum-viewer/blob/8ce5b9e1491baed1222d9f80303b320fe8fb500d/_includes/pdfkit.html#L135-L233

The single page function, generatePdfShapshot:

https://github.com/humdrum-tools/verovio-humdrum-viewer/blob/8ce5b9e1491baed1222d9f80303b320fe8fb500d/_includes/pdfkit.html#L24-L131

scales the SVG image to the width of a letter-sized page, rotating the page depending on the aspect ratio of the online SVG image.

But the `SVGtoPDF` function should allow multiple SVG images to be overlapped on the same PDF page.

--------

Example implementation:

On VHV, type alt-t to download the PDF of the visible SVG on the page (see the downloaded file at the bottom of the window):

screen shot 2017-10-16 at 12 11 40 am

opening the PDF in the web browser:

screen shot 2017-10-16 at 12 11 25 am

Musical score:

```
**kern
4c
4d-i
4enj
4f#k
*-
!!!RDF**kern: i = marked note color=limegreen
!!!RDF**kern: j = marked note color=hotpink
!!!RDF**kern: k = marked note color=chocolate
```

SVG image (type alt-g to display SVG of image in new window):

```svg
<svg width="258.80px" height="116.80px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" overflow="visible">
	<desc>Engraved by Verovio 2.0.0-dev-ae70647-dirty</desc>
	<defs>
		<symbol id="E050" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M441 -245c-23 -4 -48 -6 -76 -6c-59 0 -102 7 -130 20c-88 42 -150 93 -187 154c-26 44 -43 103 -48 176c-4 60 11 123 44 189c29 57 65 106 110 148s96 85 153 127c-3 16 -8 46 -13 92c-4 43 -5 73 -5 89c0 117 16 172 69 257c34 54 64 82 89 82c21 0 43 -30 69 -92 s39 -115 41 -159c2 -120 -19 -173 -67 -256c-13 -20 -63 -90 -98 -118c-13 -9 -25 -19 -37 -29l31 -181c8 1 18 2 28 2c58 0 102 -12 133 -35c59 -43 92 -104 98 -184c11 -135 -80 -229 -180 -270c8 -57 17 -110 25 -162c5 -31 6 -58 6 -80c0 -30 -5 -53 -14 -70 c-35 -64 -88 -99 -158 -103c-42 -3 -83 6 -124 26c-50 24 -77 59 -80 105c-2 34 5 63 20 87c18 28 45 42 79 44c51 4 99 -40 103 -87c4 -56 -30 -94 -105 -115c17 -24 51 -36 102 -36c62 0 116 43 140 85c9 16 13 41 13 74c0 20 -1 42 -5 67c-8 53 -18 106 -26 159zM461 939 c-95 0 -135 -175 -135 -286c0 -24 2 -48 5 -71c50 39 92 82 127 128c43 57 63 106 60 148c-4 54 -23 82 -57 81zM406 119l54 -326c80 27 116 88 109 184c-7 99 -62 146 -163 142zM382 117c-74 -2 -132 -50 -128 -127c2 -46 43 -99 75 -115c-3 -2 -7 -5 -10 -10 c-70 33 -116 88 -123 172c-5 73 42 135 88 170c23 17 49 29 78 36l-29 170c-21 -13 -52 -37 -92 -73c-50 -44 -86 -84 -109 -119c-49 -75 -71 -140 -67 -195c5 -68 35 -127 93 -176s125 -73 203 -73c25 0 50 3 75 9c-19 111 -36 221 -54 331z" />
		</symbol>
		<symbol id="E0A4" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M0 -39c0 68 73 172 200 172c66 0 114 -37 114 -95c0 -84 -106 -171 -218 -171c-64 0 -96 30 -96 94z" />
		</symbol>
		<symbol id="E260" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M20 110c32 16 54 27 93 27c26 0 35 -3 54 -13c13 -7 24 -20 27 -38l4 -25c0 -28 -16 -57 -45 -89c-23 -25 -39 -44 -65 -68l-88 -79v644h20v-359zM90 106c-32 0 -48 -10 -70 -29v-194c31 31 54 59 71 84c21 32 32 59 32 84c0 9 1 16 1 20c0 14 -3 21 -11 30l-8 3z" />
		</symbol>
		<symbol id="E261" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M0 -188v539h18v-191l139 22v-533h-17v186zM18 -100l122 17v176l-122 -19v-174z" />
		</symbol>
		<symbol id="E262" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M136 186v169h17v-164l44 14v-91l-44 -14v-165l44 12v-91l-44 -13v-155h-17v150l-76 -22v-155h-17v149l-43 -13v90l43 14v167l-43 -14v92l43 13v169h17v-163zM60 73v-167l76 22v168z" />
		</symbol>
	</defs>
	<style type="text/css">g.page-margin{font-family:Times;} g.tempo{font-weight:bold;} g.dir, g.dynam{font-style:italic;} g.label{font-weight:normal;}</style>
	<svg class="definition-scale" viewBox="0 0 6470 2920">
		<g class="page-margin" transform="translate(200, 200)">
			<g class="system" id="system-0000000045184246">
				<g class="section boundaryStart" id="section-0000000633354161" />
				<g class="measure m-0" id="measure-L1">
					<g class="staff" id="staff-0000001756290284">
						<path d="M0 1100 L6070 1100" stroke="#000000" stroke-width="20" />
						<path d="M0 1280 L6070 1280" stroke="#000000" stroke-width="20" />
						<path d="M0 1460 L6070 1460" stroke="#000000" stroke-width="20" />
						<path d="M0 1640 L6070 1640" stroke="#000000" stroke-width="20" />
						<path d="M0 1820 L6070 1820" stroke="#000000" stroke-width="20" />
						<g class="clef">
							<use xlink:href="#E050" x="90" y="1640" height="720px" width="720px" />
						</g>
						<g class="ledgerLines below">
							<path d="M806 2000 L1132 2000" stroke="#000000" stroke-width="35" />
						</g>
						<g class="layer" id="layer-L1F1N1">
							<g class="note qon-0 qoff-1 pname-c acc-n oct-4 b40c-2 b12c-0 " id="note-L2F1">
								<use xlink:href="#E0A4" x="856" y="2000" height="720px" width="720px" />
								<g class="stem" id="stem-0000000857041902">
									<rect x="1062" y="1370" height="608" width="20" />
								</g>
								<g class="accid" id="accid-0000001249550814" />
							</g>
							<g class="note marked qon-1 qoff-2 pname-d acc-f oct-4 b40c-7 b12c-1 " id="note-L3F1" fill="limegreen">
								<use xlink:href="#E0A4" x="2156" y="1910" height="720px" width="720px" />
								<g class="stem" id="stem-0000001808375064">
									<rect x="2362" y="1280" height="608" width="20" />
								</g>
								<g class="accid" id="accid-0000001767483164">
									<use xlink:href="#E260" x="1954" y="1910" height="720px" width="720px" />
								</g>
							</g>
							<g class="note marked qon-2 qoff-3 pname-e acc-n oct-4 b40c-14 b12c-4 " id="note-L4F1" fill="hotpink">
								<use xlink:href="#E0A4" x="3456" y="1820" height="720px" width="720px" />
								<g class="stem" id="stem-0000000960156118">
									<rect x="3662" y="1190" height="608" width="20" />
								</g>
								<g class="accid" id="accid-L4F1">
									<use xlink:href="#E261" x="3283" y="1820" height="720px" width="720px" />
								</g>
							</g>
							<g class="note marked qon-3 qoff-4 pname-f acc-s oct-4 b40c-20 b12c-6 " id="note-L5F1" fill="chocolate">
								<use xlink:href="#E0A4" x="4756" y="1730" height="720px" width="720px" />
								<g class="stem" id="stem-0000000288637444">
									<rect x="4962" y="1100" height="608" width="20" />
								</g>
								<g class="accid" id="accid-0000001728861734">
									<use xlink:href="#E262" x="4555" y="1730" height="720px" width="720px" />
								</g>
							</g>
						</g>
					</g>
					<g class="barLineAttr" id="bline-0000000463182087">
						<path d="M6055 1100 L6055 1820" stroke="#000000" stroke-width="30" />
					</g>
				</g>
				<g class="boundaryEnd section-0000000633354161" id="bdend-0000001565679642" />
			</g>
		</g>
	</svg>
</svg>
```

Downloaded PDF file:

[data-snapshot.pdf](https://github.com/sul-cidr/josquin-ribbon/files/1386483/data-snapshot.pdf)

**Comment by seemantk** [comment]
The issue isn't about multiple images overwriting, but that the markings SVG is based on the measurements of the viewing screen when the webpage is loaded -- the markings are dynamic, which is how d3 does it.

The trick here would be to resize the markings svg to the full width during export.

**Comment by curran** [comment]
I'm sort of stuck on this one, not sure how we can make it work.

**Comment by curran** [comment]
Closing as "wontfix"

**Pull request closed without merging**
